apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
spec:
  replicas: 1  # Number of replicas for scalability
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
      - name: task-api
        image: monyslim/task-api:1.0.0 # Replace with your DockerHub username
        ports:
        - containerPort: 8000
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: task-api-service
spec:
  type: LoadBalancer  # Change to NodePort if using Minikube
  selector:
    app: task-api
  ports:
    - protocol: TCP
      port: 80    # Exposed port
      targetPort: 8000  # Container port

