name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          NAME: task-api
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}  # Shorten SHA for unique tagging
          docker build -t ${DOCKER_USERNAME}/${NAME}:${IMAGE_TAG} .
          docker tag ${DOCKER_USERNAME}/${NAME}:${IMAGE_TAG} ${DOCKER_USERNAME}/${NAME}:latest
          docker push ${DOCKER_USERNAME}/${NAME}:${IMAGE_TAG}
          docker push ${DOCKER_USERNAME}/${NAME}:latest

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status

      - name: Configure kubectl for Minikube
        run: |
          kubectl config use-context minikube
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to Minikube
        run: | 
          kubectl apply -f deployment.yaml
          kubectl apply -f ingress.yaml
      - name: Wait for Pods to be Ready
        run: |
          echo "Waiting for pods to be in Running state..."
          while [[ $(kubectl get pods -n default --field-selector=status.phase!=Running | wc -l) -gt 1 ]]; do
            echo "Still waiting for pods..."
            kubectl get pods -n default
            sleep 10
          done
          echo "All pods are running!"

      - name: Wait for Services to be Ready
        run: |
          echo "Waiting for services to be assigned an EXTERNAL-IP..."
          while [[ $(kubectl get svc -n default | grep task-api-service | awk '{print $4}') == "<pending>" ]]; do
            echo "Still waiting for External IP..."
            kubectl get svc -n default
            sleep 10
          done
          echo "Service is ready!"

      - name: Verify Deployment
        run: |
          kubectl get pods -A
          kubectl get svc -A
          kubectl get ingress -A
  
      - name: Clean up Minikube
        run: |
          minikube delete   