name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          NAME: task-api
        run: |
          IMAGE_TAG=1.0.0
          docker build -t ${DOCKER_USERNAME}/${NAME}:${IMAGE_TAG} .
          docker push ${DOCKER_USERNAME}/${NAME}:${IMAGE_TAG}

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status

      - name: Configure kubectl for Minikube
        run: |
          kubectl config use-context minikube
          kubectl cluster-info
          kubectl get nodes
      - name: Add monyslim.online to /etc/hosts
        run: |
            MINIKUBE_IP=$(minikube ip)
            echo "$MINIKUBE_IP monyslim.online" | sudo tee -a /etc/hosts
            echo "Updated /etc/hosts with Minikube IP: $MINIKUBE_IP"
      - name: Enable Minikube Ingress
        run: |
              minikube addons enable ingress
              sleep 10  # Give some time for the ingress controller to start
              kubectl get pods -n kube-system | grep ingress

      - name: Deploy to Minikube
        run: | 
          kubectl apply -f deployment.yaml
          kubectl apply -f ingress.yaml
      - name: Wait for Pods to be Ready
        run: |
          echo "Waiting for pods to be in Running state..."
          kubectl wait --for=condition=ready pod --all --timeout=300s
          echo "All pods are running!"

      - name: Wait for Services to be Ready
        run: |
          echo "Waiting for service to be ready..."
          while [[ $(kubectl get svc task-api-service -n default --no-headers | wc -l) -eq 0 ]]; do
            echo "Still waiting for service..."
            kubectl get svc -n default
            sleep 10
          done
          echo "Service is now ready!"
      - name: Verify Deployment
        run: |
          kubectl get pods -A
          kubectl get svc -A
          kubectl get ingress -A
  
      - name: Clean up Minikube
        run: |
          minikube delete   